apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
{{- if .Values.keycloak.hostname.enable }}
{{- with (first .Values.keycloak.hosts) }}
  KC_HOSTNAME: "{{ .protocol }}://{{ .name }}"
{{- end }}
{{- end }}
{{- if .Values.keycloak.frontendEnabled }}
  KC_ROOT_URL: "{{ .Values.keycloak.frontendProtocol }}://{{ .Values.keycloak.frontendHostname }}"
{{- end }}
  KC_HOSTNAME_STRICT:  "{{ .Values.keycloak.hostname.strict }}"
  KC_HOSTNAME_STRICT_HTTPS: "{{ .Values.keycloak.hostname.strictHTTPS }}"
{{- if .Values.keycloak.httpRelativePath }}
  KC_HTTP_RELATIVE_PATH: "{{.Values.keycloak.httpRelativePath }}"
{{- end }}
  KC_PROXY_HEADERS: "xforwarded"
  KC_HTTP_ENABLED: "{{ .Values.service.http.enabled }}"
  KC_BOOTSTRAP_ADMIN_USERNAME: "{{ .Values.auth.adminUsername }}"
  KC_HTTP_MANAGEMENT_PORT: "8090"
  JAVA_OPTS_APPEND: {{ printf "-Djgroups.dns.query=%s.%s.svc.cluster.local" (include "common.headlessServiceName" .) (include "common.names.namespace" .) | quote }}
  KC_HTTP_POOL_MAX_THREADS: "{{ .Values.threadPool }}"
  KC_DB: "{{ .Values.database.type }}"
