{{- if .Values.extraSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.extraSecret.name }}"
  namespace: "{{ include "common.names.namespace" . }}"
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- .Values.extraSecret.data | toYaml | nindent 2 }}

{{- end }}
