apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.headlessServiceName" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  type: "ClusterIP"
  clusterIP: "None"
