apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  type: "ClusterIP"
  ports:
    {{- if .Values.service.http.enabled }}
    - name: http
      port: 80
      targetPort: web
    {{- end }}
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: mgmt
